### ISSUE TITLE
Requirements in Kotti scaffold for Pyramid are out of sync

### ISSUE THREAD

**Issue by piotr-dobrogost** [Kotti/Kotti#446]
`kotti/scaffolds/package/requirements.txt` both in Kotti 1.1.3 and 1.1.4 links to requirements of wrong Kotti version – `-r https://raw.githubusercontent.com/Kotti/Kotti/1.1.2/requirements.txt`

**Comment by disko** [comment]
Thanks for reporting!

**Comment by piotr-dobrogost** [comment]
As this should be bumped in the process of making each release I'm wondering if there's any checkpoint for this to prevent this in the future?

**Comment by disko** [comment]
I'd love to make the scaffold's ``requirements.txt`` a template, that substitutes the Kotti version with a user provided value, the installed version of Kotti being the default).  

This would be easy (via ``pkg_resources.get_distribution("Kotti").version``).  

Unfortunately it would break our scaffold tests for non released (development) versions, because they're not available on PyPI.  If you have (or anyone else has) an idea on how to programmatically get the latest *released* version, I'm all ears.

**Comment by piotr-dobrogost** [comment]
I'm not sure how being able to programmatically get the latest released version would help here.
